#eureka-client配置
server:
  port: 8762

#配置服务名称 需要指明spring.application.name,这个很重要
spring:
  application:
    name: eureka-client

#配置注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

