server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#连接Elasitcsearch的配置如下
es:
  host: localhost
  port: 9200
  scheme: http

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml