
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #连接Elasitcsearch的配置如下
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300  #此处需注意：端口是9300,9200是客户端访问的

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml